version: '3'

services:

  dh1:
    build:
      context: hello-world-service-1/.
      dockerfile: Dockerfile
    image: whoan/hello-world-service-1:latest
    depends_on:
      - redis
    environment:
      API_PORT: 80

  dh2:
    build:
      context: hello-world-service-2/.
      dockerfile: Dockerfile-custom
    image: whoan/hello-world-service-2
    restart: always

  ignored:
    build:
      context: ignored/.
      dockerfile: Dockerfile
    image: unexistent/foo/bar/baz:latest

  gh:
    build:
      context: .
      dockerfile: Dockerfile-gh
    image: docker.pkg.github.com/whoan/hello-world/gh:latest

  redis:
    image: redis:5
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
