version: '3'

services:

  dh1:
    build: unexistent/.
    image: whoan/hello_world_service-1:latest
    depends_on:
      - redis
    environment:
      API_PORT: 80

  dh3:
    image: whoan/hello_world_service-3:latest

  gh:
    build:
      context: .
      dockerfile: Dockerfile-gh
      args:
        FOO: bar
        SOME: "thing here"
    image: ghcr.io/whoan/hello-world/gh:latest

  gh_2:
    build:
      context: .
      dockerfile: Dockerfile-gh2
    image: ghcr.io/whoan/hello-world/gh-2:latest # some comment here

  gh_3: &service-config
    my_key: my_val
  gh_4:
    <<: *service-config
    image: ghcr.io/whoan/hello-world/gh-4:latest

  gh_some_thing:
    build: .
    image: ghcr.io/whoan/hello-world/some-thing:latest

  gh_some:
    build: .
    image: ghcr.io/whoan/hello-world/some:latest

  redis:
    image: redis:5
