version: '3'

services:

  hello-world-service-1:
    build:
      context: hello-world-service-1/.
      dockerfile: Dockerfile
    image: whoan/hello-world-service-1:latest
    depends_on:
      - redis
    environment:
      API_PORT: 80

  hello-world-service-2:
    build:
      context: hello-world-service-2/.
      dockerfile: Dockerfile-custom
    image: whoan/hello-world-service-2
    restart: always

  mars:
    build:
      context: mars/.
      dockerfile: Dockerfile
    image: docker.pkg.github.com/foo/bar/baz:latest
    restart: always

  redis:
    image: redis:5
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
