name: docker-compose

on: [push]

jobs:

  build-compose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        compose_file: docker-compose.yml > docker-compose.override.yml

    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: whoan
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: ghcr.io
        compose_file: docker-compose.yml

    - name: Service regex (Docker Hub)
      uses: whoan/docker-build-with-cache-action@master
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        compose_file: docker-compose.yml > docker-compose.override.yml
        services_regex: '(dh.*|gh_some)'

    - name: Service regex (GitHub Registry)
      uses: whoan/docker-build-with-cache-action@master
      with:
        username: whoan
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: ghcr.io
        compose_file: docker-compose.yml
        services_regex: '(dh.*|gh_some)'

  build-compose-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        context: foo
        compose_file: foo/docker-compose.yml
