name: docker-compose

on: [push]

jobs:

  build-compose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: whoan/docker-build-with-cache-action@issue-128
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        compose_file: docker-compose.yml > docker-compose.override.yml

    - uses: whoan/docker-build-with-cache-action@issue-128
      with:
        username: whoan
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        compose_file: docker-compose.yml
