name: docker-hub

on: [push]

jobs:

  build-dh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@v6
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        build_extra_args: '{"--build-arg": ["foo=bar", "one=two"], "--target": "one-target"}'
        image_name: hello-world
        image_tag: latest,anotherone
    - uses: whoan/docker-build-with-cache-action@v6
      id: multi-tag
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: hello-world-multi-tag
        image_tag: one,two,three
    - name: Get full image name from multi-tag step
      run: echo "Full image name -> ${{ steps.multi-tag.outputs.FULL_IMAGE_NAME }}"
