name: docker-hub

on:
  schedule:
    - cron:  '38 10 * * *'

jobs:

  build-dh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: hello-world
