name: docker-hub

on: [push]

jobs:

  build-dh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@next
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        build_extra_args: '{"--build-arg": ["foo=bar", "one=two"], "--target": "one-target"}'
        image_name: hello-world
        image_tag: latest,anotherone

    - uses: whoan/docker-build-with-cache-action@next
      id: multi-tag
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: hello-world-multi-tag
        image_tag: one,two,three
    - name: Get full image name from multi-tag step
      run: echo "Full image name -> ${{ steps.multi-tag.outputs.FULL_IMAGE_NAME }}"

    - name: Build with DOCKER_BUILDKIT enabled
      env:
        DOCKER_BUILDKIT: 1
      uses: whoan/docker-build-with-cache-action@next
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: hello-world-buildkit

    - name: Build without DOCKER_BUILDKIT enabled
      env:
        DOCKER_BUILDKIT: 0
      uses: whoan/docker-build-with-cache-action@next
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: hello-world-no-buildkit

  build-dh-v1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: whoan/docker-build-with-cache-action@v1
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: whoan/hello-world-v1

  build-dh-v2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: whoan/docker-build-with-cache-action@v2
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: whoan/hello-world-v2

  build-dh-v3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: whoan/hello-world-v3

  build-dh-v4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: whoan/docker-build-with-cache-action@v4
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: whoan/hello-world-v4

  build-dh-v5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: hello-world-v5

  build-dh-v6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: whoan/docker-build-with-cache-action@v6
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: hello-world-v6

  build-dh-v7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: whoan/docker-build-with-cache-action@v7
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: hello-world-v7
