name: docker-hub

on: [push]

jobs:

  build-dh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@fix-json-extra-args
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        build_extra_args: "--build-arg=PARAM=value --build-arg=PARAM1=value1 --build-arg=PARAM2=value2 "
        image_name: hello-world
        image_tag: latest,anotherone
