name: docker-hub

on: [push]

jobs:

  build-dh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@support-json-for-extra-build-args
      with:
        username: whoan
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        build_extra_args: '{"--build-arg": "myarg=hola\nmundo"}'
        image_name: hello-world
        image_tag: latest,anotherone
